/* Base Product tables*/
create table if not exists category (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, name varchar(100) not null, parentid bigint, CONSTRAINT FOREIGN KEY(parentid) REFERENCES category(rootid));
create table if not exists product (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, categoryid bigint, name varchar(100) not null, description varchar(512), rating decimal(2,2), measurement varchar(16) not null, refridgerated BOOL DEFAULT FALSE, CONSTRAINT FOREIGN KEY(categoryid) REFERENCES category(rootid));
create table if not exists productinfo (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, mrp int, discount int, price int, image varchar(1024), size  varchar(16), productid bigint, autopurchase BOOL DEFAULT FALSE, CONSTRAINT FOREIGN KEY(productid) REFERENCES product(rootid));
create table if not exists productinventory (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, productinfoid bigint, quantityavailable int, barcode varchar(32), expiry varchar(10), UNIQUE KEY `product_barcode` (`barcode`,`tenantid`), CONSTRAINT FOREIGN KEY(productinfoid) REFERENCES productinfo(rootid));
create table if not exists productspecifications (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, productinfoid bigint, specifications json, images json, CONSTRAINT FOREIGN KEY(productinfoid) REFERENCES productinfo(rootid));

create table if not exists productkeyindex (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, searchtext varchar(1024), productid bigint, CONSTRAINT FOREIGN KEY(productid) REFERENCES product(rootid));

create table if not exists productsupplierinfo (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, productid bigint, supplierid bigint, CONSTRAINT FOREIGN KEY(productid) REFERENCES product(rootid), CONSTRAINT FOREIGN KEY(supplierid) REFERENCES supplier(rootid));
create table if not exists producthistory (rootid bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, tenantid bigint NOT NULL, timecreated bigint DEFAULT 0, timeupdated bigint DEFAULT 0, active BOOL DEFAULT TRUE, modifiedby bigint DEFAULT 0, createdby bigint DEFAULT 0, version bigint DEFAULT 0, barcode varchar(32) NOT NULL, recievedate DATETIME, quantity int);