apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-spring-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-name-spring-app
  template:
    metadata:
      labels:
        app: release-name-spring-app
    spec:
      containers:
          - name: release-name-spring-app-container
            image: manivannan11/tenent
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8081
            env:
              - name: SPRING_DATASOURCE_URL
                value: "jdbc:mysql://mysql:3306/tenantmanagement?useSSL=false&allowPublicKeyRetrieval=true"
              - name: SPRING_DATASOURCE_USERNAME
                value: root
              - name: SPRING_DATASOURCE_PASSWORD
                value: root1234